
num_hidden_layers: 6
hidden_size: 256
filter_size: 512
num_heads: 8

initializer_gain: 1.0

relu_dropout: 0.3
attention_dropout: 0.3
layer_postprocess_dropout: 0.1

allow_ffn_pad: True

batch_size: 256
evaluate_every_steps: 10
