# 优化器的参数
optimizer:
  clip_gradients: 5
  learning_rate: 0.01

global:
  max_seq_len: 20
  embedding_dim: 512

# 注意力层的参数
attention:
  use_attention: True
  attention_num_units: 512

# 编码层的参数
encoder:
  use_bilstm: True
  rnn_cell_type: LSTMCell
  rnn_num_units: 512
  dropout_input_keep_prob: 0.8
  dropout_output_keep_prob: 1.0
  num_layers: 2

# 解码层的参数
decoder:
  rnn_cell_type: LSTMCell
  rnn_num_units: 512
  dropout_input_keep_prob: 0.8
  dropout_output_keep_prob: 1.0
  num_layers: 4